from datalab_sdk.api.exceptions import InputNotValid, ResourceNotFound

class RecipeNotFound(ResourceNotFound):
    """Raised when the requested info not found in Recipe"""
    def __init__(self, correlation_id: str = None):
        super().__init__(f"The requested info for recipe not found", correlation_id)