from datalab_sdk.api.exceptions import InputNotValid, ResourceNotFound

class SpsNotFound(ResourceNotFound):
    """Raised when the requested info not found in sps"""
    def __init__(self, correlation_id: str = None):
        super().__init__(f"The requested info for sps not found", correlation_id)