import jwt
from logging import debug, error
from flask import request
from datalab_sdk.api.exceptions import AuthNotValid
from datalab_sdk.config.environment import Environment, EnvironmentConfig
from datalab_sdk.auth.asynchronous import BaseAuth
from typing import Union

# Auth implementation for user apps API use only
class PlatformAuth(BaseAuth):

    def __init__(self):
        # only applies to ON_PLATFORM env
        super().__init__(environment=Environment.ON_PLATFORM)

    # gets the token from the current call context
    def get_token(self) -> str:
        if EnvironmentConfig.in_notebook():
            return "" # no token necessary inside a notebook
        elif "x-auth-jwt" in request.headers:
            return request.headers["x-auth-jwt"]
        debug(request.headers)
        raise AuthNotValid("Unable to find current token")

    def is_valid(self, token: str) -> bool:
        # in the platform context can't access the app without token
        # so all need to check is that is a JWT
        try:
            claims = jwt.decode(token, algorithms=["HS256"], options={"verify_signature": False})
            return len(claims) > 0 and self._is_in_time(claims)
        except Exception as e:
            error(e)
            return False
