from datalab_sdk.api.exceptions import InputNotValid, ResourceNotFound

class HpcNotFound(ResourceNotFound):
    """Raised when the requested info not found in Hpc"""
    def __init__(self, correlation_id: str = None):
        super().__init__(f"The requested info for hpc not found", correlation_id)